/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package grados_combo;

/**
 *
 * @author soloj
 */
public class Grados extends javax.swing.JFrame {

    /**
     * Creates new form Grados
     */
    public Grados() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        this.setLocationRelativeTo(null);
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtingresar_grados = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        combo_grados = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtresultado = new javax.swing.JTextField();
        lblgrados = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Conversor de Grados");

        jLabel2.setText("Ingresa los grados a convertir");

        jLabel3.setText("Elija una opción:");

        combo_grados.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "°C -- °F", "°F -- °C", "°C -- °K", "°K -- °C", "°F -- °K", "°K -- °F", "°C -- °R", "°F -- °R" }));
        combo_grados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_gradosActionPerformed(evt);
            }
        });

        jLabel4.setText("Resultado:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addComponent(txtingresar_grados))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(combo_grados, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtresultado, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblgrados, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtingresar_grados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(combo_grados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtresultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblgrados, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void combo_gradosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_gradosActionPerformed
      
        double numero1=Double.parseDouble(txtingresar_grados.getText());
        
        if(combo_grados.getSelectedItem().toString().equals("°C -- °F"))
           {
              double celcius=32+(9*numero1/5);
              txtresultado.setText(String.valueOf(celcius));
              lblgrados.setText("°F");
           }
        
        else if(combo_grados.getSelectedItem().toString().equals("°F -- °C"))
            {
               double farenheit=(numero1-32)*5/9;
               txtresultado.setText(String.valueOf(farenheit));
               lblgrados.setText("°C");
            }

        else if(combo_grados.getSelectedItem().toString().equals("°C -- °K"))
        {
            double celcius=273.15+numero1;
            txtresultado.setText(String.valueOf(celcius));
            lblgrados.setText("°K");
        }

        else if(combo_grados.getSelectedItem().toString().equals("°K -- °C"))
        {
            double celcius=numero1-273.15;
            txtresultado.setText(String.valueOf(celcius));
            lblgrados.setText("°C");
        }

        else if(combo_grados.getSelectedItem().toString().equals("°F -- °K"))
        {
            double celcius=((numero1-32)*5/9)+273.15;
            txtresultado.setText(String.valueOf(celcius));
            lblgrados.setText("°K");
        }

        else if(combo_grados.getSelectedItem().toString().equals("°K -- °F"))
        {
            double celcius=((numero1-273.15)*9/5+32);
            txtresultado.setText(String.valueOf(celcius));
            lblgrados.setText("°F");
        }

        else if(combo_grados.getSelectedItem().toString().equals("°C -- °R"))
        {
            double celcius=((numero1*9/5)+491.67);
            txtresultado.setText(String.valueOf(celcius));
            lblgrados.setText("°R");
        }

        else if(combo_grados.getSelectedItem().toString().equals("°F -- °R"))
        {
            double celcius=((numero1+459.67));
            txtresultado.setText(String.valueOf(celcius));
            lblgrados.setText("°R");
        }
    }//GEN-LAST:event_combo_gradosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Grados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Grados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Grados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Grados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Grados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> combo_grados;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblgrados;
    private javax.swing.JTextField txtingresar_grados;
    private javax.swing.JTextField txtresultado;
    // End of variables declaration//GEN-END:variables
}
